name: Run build checks

on:
  pull_request:

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          version: 1.0.0

      - name: Install Dependencies
        run: |
          bun i
          bun run build
          ls -l
